language: c
before_install:
  - curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
  - sudo apt-get -q update
install:
  - sudo apt-get install crystal
script:
  - make spec
before_deploy:
  - make release
deploy:
  provider: releases
  api_key:
    secure: VPNhmZR0qN7bZKcjA0BhtwaWpqlbMZWvtwYoUkqUdBE9tDG4c8llGrVRTk5Xd6RX5rPoWcR0JY+tq3vdIkVvlIW2pH/iMdwlIHapEtYOLpVTGQ3ikknLcqsR/EcOxUZxBNQCFiVDnC3Pn3vfLzpLLhCsTUkEq8RQLmjISjZnJ3E=
  file: crul
  on:
    tags: true
